# Generated by Django 5.0.6 on 2024-05-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.TextField(default='default', max_length=1000),
            preserve_default=False,
        ),
    ]
